- hosts: private_ipsec_fra

  tasks:
    - name: ensure a list of packages installed
      become: yes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - pacemaker    
          - pcs
          - resource-agents
          - git
          - jq

    #
    # prepare configuration
    #
    - name: create ipsec partner cfg directory
      become: yes
      file:
        path: /etc/ipsec_partner
        state: directory
        mode: "0700"

    - name: create ipsec partner state directory
      become: yes
      file:
        path: /opt/ipsec-partner/state
        state: directory
        mode: "0700"

    - name: copy cluster configuration
      become: yes
      copy:
        src: ipsec_cluster.config
        dest: /etc/ipsec_partner
        force: yes
        mode: "0400"

    #
    # register secondary vnic cfg servcie
    #
    - name: register secondary vnic cfg servcie
      become: yes
      script: register_secondary_vnic_unit.sh

    #
    # prepare cluster nodes
    #
    - name: prepare cluster node
      become: yes
      script: pacemaker_cluster_node_prepare.sh /etc/ipsec_partner/ipsec_cluster.config

    #
    # configure cluster - run only on one node
    #
    - name: init pacemaker cluster
      become: yes
      script: pacemaker_cluster_init.sh /etc/ipsec_partner/ipsec_cluster.config
      when: ipsec_cluster_role is defined and ipsec_cluster_role == 'master'

    - name: init libreswan cluster
      become: yes
      script: ipsec_cluster_3nic_init.sh /etc/ipsec_partner/ipsec_cluster.config
      when: ipsec_cluster_role is defined and ipsec_cluster_role == 'master'
