- hosts: all
  vars:
    ipsec_key: oci_api_key_ipsec.pem

  tasks:
    - name: ensure a list of packages installed
      become: yes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - expect
          - python3
          - curl

    #
    # copy configuration
    #
    - name: create oci home directory
      become: yes
      file:
        path: ~/.oci
        state: directory
        mode: "0700"

    - name: copy config
      become: yes
      copy:
        src: config
        dest: ~/.oci
        force: yes
        mode: "0400"

    - name: copy key
      become: yes
      copy:
        src: "{{ ipsec_key }}"
        dest: ~/.oci
        force: yes
        mode: "0400"

    #
    # run assisted OCI CLI install
    #
    - name: run assisted OCI CLI install
      become: yes
      script: install_oci_cli.sh
      args:
        creates: /opt/ipsec-partner/state/register_secondary_vnic_unit.done

    #
    # run OCI test call
    #
    - name: run assisted OCI CLI install
      become: yes
      shell: oci iam availability-domain list
      register: oci_test_result

    - debug: "msg=out={{ oci_test_result.stdout }}, err: {{ oci_test_result.stdout }}"